os: linux
dist: focal
language: generic

services:
  - docker

before_install:
  - docker build -t markstanden/docker-learning -f Dockerfile.dev .

script:
  - docker run -e CI=true markstanden/docker-learning npm run test

